-- Create Trips Table
create table public.trips (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  amount numeric not null,
  odometer numeric not null,
  timestamp bigint not null,
  distance numeric default 0,
  gas_price numeric default 0,
  mpg numeric default 24
);

-- Create Session Table (Single row implementation for MVP)
create table public.sessions (
  id bigint generated by default as identity primary key,
  status text check (status in ('idle', 'active', 'paused')) default 'idle',
  meta numeric default 0,
  initial_odometer numeric default 0,
  start_time bigint,
  end_time bigint,
  total_paused_time bigint default 0,
  last_pause_time bigint
);

-- Seed initial session row (so we can just update it)
insert into public.sessions (id, status) values (1, 'idle');

-- Enable Row Level Security (Recommended for production, but optional for quick MVP if public)
alter table public.trips enable row level security;
alter table public.sessions enable row level security;

-- Create Policy: Allow Public Read/Write (Easiest for this MVP without Auth)
create policy "Public Access Trips" on public.trips for all using (true);
create policy "Public Access Sessions" on public.sessions for all using (true);
